# This workflow will build and test a Node.js project
name: Deploy to Firebase Functions via github action

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    permissions:
        checks: write
        pull-requests: write

    steps:
      - name: Lint with ESLint
        run: DEBUG=eslint:cli-engine npx eslint .
