# This workflow will build and test a Node.js project
name: Deploy to Firebase Functions via github action

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    permissions:
        checks: write
        pull-requests: write

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node v18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: .
        run: find ./* -maxdepth 2 -name package.json -execdir npm ci \;
