# This is a basic workflow to help you get started with Actions

name: Deploy to Firebase Functions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job_id:
    runs-on: 'ubuntu-latest'
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
          credentials_json: ${{ secrets.credentials_json }}
          service_account: 'firebase-adminsdk-e5bp0@proctrac.iam.gserviceaccount.com'

    - id: 'deploy'
      uses: 'jxw1102/action-functions-deploy@0.7.1'
      with:
        firebaseServiceAccount: "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS  }}"
        projectId: "${{ secrets.FIREBASE_PROJECT }}"
